package org.omg.Messaging;


/**
* org/omg/Messaging/SYNC_WITH_TRANSPORT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-owindows-i586-cygwin/jdk8u40/2855/corba/src/share/classes/org/omg/PortableInterceptor/Messaging.idl
* Tuesday, February 10, 2015 10:08:00 PM PST
*/

public interface SYNC_WITH_TRANSPORT
{

  /**
   * Constant, defined in the Messaging spec, to define how far the 
   * request shall progress before control is returned to the client.
   */
  public static final short value = (short)(1);
}
